---
- name: Add line in File Playbook
  hosts: all
  become: true
  tasks:
    - lineinfile:
        path: /etc/httpd/conf.d/demo.conf
        insertbefore: Mubmai
        line: Bye Nagpur
        insertafter: Nagpur
        line: Nagpur
        regexp:
        line: Mumbai
    - debug:
        msg: "Message Add"
