---
- name: Add line in File Playbook
  hosts: all
  become: true
  tasks:
    - lineinfile:
        path: /etc/httpd/conf.d/demo.conf
        insertbefore: 
        line: Bye Nagpur
        # insertafter:
        # line: Bye Nagpur
    - debug:
        msg: "Message Add"
