---
- name: Add line in File Playbook
  hosts: all
  become: true
  tasks:
    - lineinfile:
        path: /etc/httpd/conf.d/demo.conf
        # # insertbefore: 
        # # line: Bye Nagpur
        # insertafter:
        # # line: Nagpur
        # regexp:
        line: Mumbai
    - debug:
        msg: "Message Add"
