---
- name: Playbook
  hosts: all
  become: yes
  tasks: 
    - name: Install Apache web server
      action: yum -y name=httpd 
        state: latest

    - name: index.html
      copy:
         content: "This is Ansible Playbook"
         dest: /var/www/html/index.html
      
    - name: restart httpd
      service:
          name: httpd
          state: restarted
          enabled: yes

        
      