# Sample file of the first program of the YAML Language
# Simply Print message using debug module
---
- name: Playbook1
  hosts: all
  tasks:
  - name: Print Host Details
    debug:
      msg: Domain name of ansible: "{{ansible domain}}"