---
- name: Find In Playbook
  hosts: all
  become: true
  tasks:
    - name: Find or sorting
      find:
        path: /etc/ssh
        file_type: file
        pattern: "*pub"
      register: Bhushan

    - name: print sorted file
      debug:
        msg: "{{Bhushan}}"

    # - debug:       
    #     msg: "{{item.path}}" 
    #   loop: "{{Bhushan.files}}"


      # Delete Sorted File
    - name: Delete sorted file
      file:
        path: "{{item.path}}"
        state: absent
      loop: "{{Bhushan.files}}"
