---
- name: Ignore Error Playbook
  hosts: all
  become: true
  tasks:
    - name: get output
      shell: ps -elf | grep sleep | grep -v grep
      ignore_errors: yes

    - name: print message
      debug: 
        msg: "Hello World"