# Local Variable
# Simply Print message using debug module
---
- name: Playbook1
  hosts: all
  vars:
    URL: Global.Cloudblitz.in
  
  tasks:
  - name: Print Message_1
    debug:
      msg: "{{URL}}"

  vars:
    URL: Local.Cloudblitz.in
  