# explore loops in playook
---
- name: loop Playbook
  hosts: all
  become: yes
  tasks:
    - name: Print Linux services Name
      debug:
        msg: "All Service Name In Linux are : {{item}}"
      loop:
        - HTTP
        - SSH
        - NFS
        - FTP
        - DNS
        - DHCP

    - name: Install Packages
      yum:
        name: "{{item}}"
        state: latest
      loop:
        - httpd
        - vim 
        - tree
        - ansible