# In Comparison of Local Variable vs Global Variable vs Variable-File vs Prompt Variable
# The Priority Give to Local Variable
# Simply Print message using debug module
---
- name: Playbook1
  hosts: all
  vars:
    URL: Global.Cloudblitz.in
  
  tasks:
  - name: Print Message_1
    debug:
      msg: "{{URL}}"

  vars:
    URL: Local.Cloudblitz.in

  vars_files: URL.yml

  vars_prompt:
  - name: URL
    prompt: "ENTER URL"   
    private: no