---
- name: install tomcat server
  hosts: all
  become: true
  vars: 
    tomcat_url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.81/bin/apache-tomcat-8.5.81.tar.gz
    tomcat_package: apache-tomcat-8.5.81
  tasks: 
  - name: Update repos
    yum:
      name: "*"
      state: latest

  - name: install java OpenJDK
    yum: 
      name: java-1.8.0-openjdk
      state: present
     
  - name: download tomcat server packages
    get_url: 
       url: "{{tomcat_url}}"
       dest: /usr/local

  - name: extract tomcat packages
    unarchive:  
       src: "/usr/local/{{tomcat_package}}.tar.gz"
       dest: /usr/local
       remote_src: yes

  - name: start tomcat services
    shell: nohup /usr/local/{{tomcat_package}}/bin/startup.sh

