---
- name: install tomcat server
  hosts: all
  become: true
  vars: 
    - tomcat_url: https://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.63/bin/apache-tomcat-8.5.63.tar.gz
    - tomcat_package: apache-tomcat-8.5.63

  tasks: 
  - name: install java
    apt: 
     name: openjdk-8-jdk
     state: present
     
  - name: download tomcat server packages
    get_url: 
      url: "{{tomcat_url}}"
      dest: /usr/local

  - name: extract tomcat packages
    unarchive:  
      src: /usr/local/{{tomcat_package}}.tar.gz
      dest: /usr/local
      remote_src: yes


  - name: start tomcat services
    shell: nohup /usr/local/{{tomcat_package}}/bin/startup.sh

