# In Comparison of Local Variable vs Global Variable vs Variable-File 
# The Priority Give to Variable-File
# Simply Print message using debug module
---
- name: Playbook1
  hosts: all
  vars:
    URL: Global.Cloudblitz.in
  
  tasks:
  - name: Print Message_1
    debug:
      msg: "{{URL}}"

  vars:
    URL: Local.Cloudblitz.in
  
  vars_files: URL.yml


#  TO Check CLI variable priority enter following cmd on CLI mode
# ansible-playbook var_file.yml -e URL=Aws.in
# In Comparison of Local Variable vs Global Variable vs Variable-File vs CLI 
# The Priority Give to CLI