---
# tasks file for tomcatsrv
- name: Update Repos On Node
  apt:
    name: "*"
    update_cache: yes
    state: latest

- name: Install Packages
  apt:
    name: "{{item}}"
    state: latest
  loop:
      - unzip
      - openjdk-8-jdk
    
    