---
# tasks file for tomcatsrv
- name: Update Repos On Node
  apt:
    name: "*"
    state: latest

- name: installing java env
  apt:
    state: present
    name: "{{ item }}"
  loop:
    - openjdk-8-jdk
    - unzip
    
# - name: Install Packages
#   apt:
#     name: "{{item}}"
#     state: latest
#   loop:
#     - openjdk-8-jdk
#     - unzip  

    