---
# tasks file for tomcatsrv
- name: Update Repos On Node
  apt:
    name: "*"
    state: latest
  

- name: Install Packages
  apt:
    name: "{{item}}"
    state: latest
  loop:
      - unzip
      - openjdk-8-jdk

- name: download tomcat server packages
  get_url: 
    url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.81/bin/apache-tomcat-8.5.81.tar.gz
    dest: /mnt

- name: extract tomcat packages
  unarchive:  
    src: /mnt/apache-tomcat-8.5.81.tar.gz
    dest: /mnt/

    
    