---
# tasks file for tomcatsrv
- name: Update Repos On Node
  apt:
    name: "*"
    state: latest

- name: Install Packages
  apt-get:
    name: "{{item}}"
    state: latest
  loop:
    - unzip
    - openjdk-8-jdk
    
    