---
# tasks file for tomcatsrv
- name: Update Repos On Node
  apt:
    name: "*"
    state: latest
  

- name: Install Packages
  apt:
    name: "{{item}}"
    state: latest
  loop:
      - unzip
      - openjdk-8-jdk

- name: download tomcat server packages
  get_url: 
    url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.81/bin/apache-tomcat-8.5.81.tar.gz
    dest: /mnt

- name: extract tomcat packages
  command: tar -xvzf /mnt/apache-tomcat-8.5.81.tar.gz -C /mnt

#move student.war file in webapps
- name: move stydent.war file
  copy:
    src: /home/ubuntu/student.war 
    dest: /mnt/apache-tomcat-8.5.81/webapps 
    remote_src: true   

- name: start tomcat services
  shell: nohup /mnt/apache-tomcat-8.5.81/bin/startup.sh

# run the catalina
- name: start tomcat application servers
  command: start /mnt/apache-tomcat-8.5.81/bin/catalina.sh

  
        
    