---
# tasks file for apache2srv
- name: Package Installation
  package:
    name: nginx
    state: present
    name: unzip
    state: present

- name: Download Template For Run On Apache Web Server
  get_url:
    url: https://www.free-css.com/assets/files/free-css-templates/download/page278/brandon.zip
    dest: /usr/share/nginx/html

- name: install package unzip
  package:
    name: unzip
    state: latest

#- name: Extracting The Downloaded Template


